### PR TITLE
[69] Method names in Bridge.Html5.Console lowercase

### PR DESCRIPTION
**Pull request by TriEdgeAI**
Fixes https://github.com/bridgedotnet/Frameworks/issues/69

### CODE REVIEW

**Comment by TriEdgeAI** [comment]
Makes sense.

**Comment by TriEdgeAI** [comment]
The stupid online editor keeps adding a newline at the end. Pfft.

**Comment by LeonidVeriga** [comment]
@TriEdgeAI, please add **Bridge** namespace into `using Bridge` or into `Bridge.Convention(Member = Con`

**Comment by TriEdgeAI** [comment]
Done.

**Pull request merged**
