### PR TITLE
Initial commit for GoogleMaps Framework

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
Hi @kcudnik. This is looking really good so far. Might have to wait to send a pull-request until more of the .cs files are ready.

**Comment by kcudnik** [comment]
There are a lot of classes in this project, i didn't wanted to add everything in one commit. This pull request contains only project which should be easier to review. If you preffer to see more files i can add another commits.

**Comment by geoffreymcgill** [comment]
It's probably best to push everything in one pull request. That way we can review as a whole and offer any suggestions. So far everything is looking great. We really appreciate you taking the time to contribute this to the community.

**Comment by DaniilVeriga** [comment]
@kcudnik, thank you for adding more classes. It all looks very good. We will review the pull request.

Also here is a related forum thread for references:
http://forums.bridge.net/forum/general/extensions-and-plugins/1814

**Comment by geoffreymcgill** [comment]
@kcudnik,

This is looking very good.

Before fully reviewing your pull request or accepting, we would need the CLA [form](http://goo.gl/forms/CvDFLA3EPO) accepted by you. You can find more information in [CONTRIBUTING.md](https://github.com/bridgedotnet/Bridge/blob/master/CONTRIBUTING.md). 

The full CLA is available [here](http://bridge.net/cla/).

When you get a chance, please review the CLA and complete the [CLA Acceptance Form](http://goo.gl/forms/CvDFLA3EPO). If you have any questions, please just let me know.

**Comment by kcudnik** [comment]
Should i resolve conflicts on this branch?

**Comment by LeonidVeriga** [comment]
@kcudnik, it would be great!

**Comment by LeonidVeriga** [comment]
Hi @kcudnik!

We are in progress of reviewing the pull request. We plan to release it along with Bridge 1.14.

The only more or less important thing I noticed so far is XML documentation. It would be great if you could add xml descriptions for classes and members.

**Comment by kcudnik** [comment]
I though about adding documentation, from first view it seems that copy/paste would be ideal since Google already have best information about those apis, but probably copy/paste would raise some copyright/policy issues, that's why i did not provide any documentation at first place. Let me know what you think about that.

**Comment by geoffreymcgill** [comment]
Hi @kcudnik - The Google Maps documentation is licensed under [Creative Commons Attribution 3.0 License](https://creativecommons.org/licenses/by/3.0/), so using within a Bridge definition file is not a problem.

**Comment by LeonidVeriga** [comment]
Hi @kcudnik,

Can I merge your Pull Request, do you plan to push any changes in near future?

**Comment by kcudnik** [comment]
Yes go ahead, thanks!

**Comment by kcudnik** [comment]
When i try to sign CLA i get this message "CLAHub Signatures by @jasonm would like permission to access your account" just want to make sure this is safe and correct behaviour.

**Comment by geoffreymcgill** [comment]
CLAHub is the service used to manage CLA acceptance for this GitHub project. More info available on CLAHub website.

https://www.clahub.com/

**Comment by matiii** [comment]
When do you plan release this framework ? I want use Bridge.NET in my project and this framework also.

**Comment by geoffreymcgill** [comment]
Unfortunately, we will not be able to accept this pull request into the **Bridge Frameworks** repo. These frameworks are best maintained by the community within independent community driven projects.

**Comment by kcudnik** [comment]
@matiii Im working on making Google.Maps framework available as my public repo in github, i just need to make some adjustments to make sure it works, i will let you know.

**Comment by kcudnik** [comment]
@matiii feel free to take a look at https://github.com/kcudnik/bridgegooglemaps, let me know if there are any things that require fixing, also after release of Bridge 16.0 this repo will require some adjustments.

**Comment by profK** [comment]
How do you set the google API key when using the Maps framework?

It woudl be good to give a "HelloWorld" example in your project's README

**Pull request closed without merging**
