### PR TITLE
Three.js library

### PR DESCRIPTION
**Pull request by michaelcheers**
I converted from typescript with [this Typescript to C# converter](https://github.com/michaelcheers/TypeScriptToCS) and edited it a little. All interface have a JSON version called JSON{name}.
The only error now is bridgedotnet/Bridge#1530 . I didn't know how to make a nuget package so I made a normal bridge package.

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
What's with all the `#pragma warning restore CS062` lines in **THREEJS.cs**?

**Comment by michaelcheers** [comment]
@geoffreymcgill, They prevent warnings: [See the msdn page about CS0626](https://msdn.microsoft.com/en-us/library/5d6ww5ft.aspx) and [See the msdn page about CS0824](https://msdn.microsoft.com/en-us/library/bb384213.aspx).

**Comment by michaelcheers** [comment]
@geoffreymcgill, I noticed that this has already been done: https://github.com/guidovanhilst/SharpThreejs.

**Comment by michaelcheers** [comment]
@geoffreymcgill, By the way I can't seem to find the New Post or New Reply even when I'm signed in.

**Comment by kcudnik** [comment]
@michaelcheers  try ` <NoWarn>1591,0626,0824</NoWarn>` in csproj file

**Comment by michaelcheers** [comment]
@kcudnik, ok. I could also pragma the whole thing eg. at the beginning of the file and end put pragmas.

**Pull request closed without merging**
