### PR TITLE
Mark .nuget/NuGet.exe as executable

### PR DESCRIPTION
**Pull request by t-nelis**
Visual Studio Team Explorer seems to clone repositories in such a way that executable bits are somehow inherited or otherwise setup so that git doesn't detect them. Contributors who use VSTE exclusively might not see any issues, but those who use other tools (including the official git commands) that respect the blob modes won't be able to execute NuGet.exe without this patch.

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
Hi @t-nelis : Thanks for the pull request.

Before reviewing your pull request, we would need the CLA [form](http://goo.gl/forms/CvDFLA3EPO) accepted. You can find more information in [CONTRIBUTING.md](https://github.com/bridgedotnet/Bridge/blob/master/CONTRIBUTING.md). 

The full CLA is available [here](http://bridge.net/cla/).

When you get a chance, please review the CLA and complete the [CLA Acceptance Form](http://goo.gl/forms/CvDFLA3EPO). If you have any questions, please just let me know.

**Comment by t-nelis** [comment]
@geoffreymcgill Sure, I can get a signature tomorrow, but I'd be easier if you applied it yourself (should you agree with the change obviously).

Suggestion: add a trivial contributions clause to your CLA. Many projects do it, and even if some definitions of "trivial" you may want to pick might not be battle-tested, I've never heard of a case where that created issues as long as you err on the side of safety when merging contribs.

I think this one would be err- *pretty* safe. As it is I have to to ask my boss to sign a document to change the mode of a file on this repo because I technically pushed the change from my work machine (and it is job-related, we're investing a bit of time for our Bridge integration). I did it because it was faster for everybody than opening an issue -- but I guess not.

I could create another identical commit this evening and push it again from my own machine so that I can sign the CLA myself, or you could apply the change yourself faster than I get the CLA signed either way, or finally we could all agree that your legal grounds are pretty solid for when I sue you for trying to relicense my disruptive mode-change invention (patent pending) without asking for my permission (I will totally do that if you dare!). That last suggestion is the trivial-contrib clause one of course: is there really a difference between merging this commit and you creating another identical one?

(Who knows I might need a signature in the future anyway but other potential contributors might look away in these scenarios.)

Your call guys ;). (Intense decision I know.)

**Comment by DaniilVeriga** [comment]
@t-nelis, thank for the feedback and suggestions.

Unfortunately, we cannot merge the pull request without a CLA signed. Certainly, if you ever sigh CLA, then it would be the easiest way to apply your contributions:) Though, signing CLA is totally up to you - please do as the most comfortable for you. 

Actually, your pull request led to an internal discussion and it turned out that our team member @fabriciomurta already did this change locally, because he faced the same issue before. He didn't submit a pull request for that, but we'll ask him to do that -related issue #36.

**Comment by fabriciomurta** [comment]
Hello, this has been fixed on bridgedotnet/Bridge#1017 as we had files on other repos as well, I've just created a "main" one there! Thank you very much for your contribution, we really appreciate it!

**Comment by t-nelis** [comment]
@fabriciomurta @DaniilVeriga Perfect, thanks.

**Pull request closed without merging**
