### PR TITLE
Fixed issue with incorrect jquery reference in template

### PR DESCRIPTION
**Pull request by maverix**
#30

Generates invalid jquery (uses & instead of $)

Example of issue http://live.bridge.net/#9f62a426ea8b07d33d53

### CODE REVIEW

**Comment by fabriciomurta** [comment]
Well, this may be a typo or maybe it worked before a somewhat similar bug appeared, according to bridgedotnet/Bridge#796. Thanks for sharing the fix!

**Comment by LeonidVeriga** [comment]
Hi @maverix, 

Thank you for the contribution. Can you please consider signing our [CLA form](https://docs.google.com/a/object.net/forms/d/12IAxRmWCk2vD-M3mj4d0ihztqKoiREpRRSVq4pEk0-k/viewform?c=0&w=1). 

There are related documents:
Contributing document
CLA document

**Comment by maverix** [comment]
@LeonidVeriga  Signed

**Comment by geoffreymcgill** [comment]
This pr will be merged on Tuesday, Jan 5.

**Comment by DaniilVeriga** [comment]
Merged. @maverix, thank you very much for reporting the issue and submitting the fix.

**Pull request merged**
